sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cygnetops/react-test npm test

after_success:
  - docker build -t krstncreyes/multi-client ./client
  - docker build -t krstncreyes/multi-nginx ./nginx
  - docker build -t krstncreyes/multi-server ./server
  - docker build -t krstncreyes/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to Docker hub
  - docker push krstncreyes/multi-client
  - docker push krstncreyes/multi-nginx
  - docker push krstncreyes/multi-server
  - docker push krstncreyes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'Multi-docker-env-1'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-674998075297'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
